name: "Issue Request"
description: Create a new ticket for a new  issue request
title: "[ISSUE] - <title>"
labels: [
  "good first issue",
  "enhancement",
  "hacktoberfest",
  
]
body:
  - type: textarea
    id: Description
    attributes:
      label: "Description"
      description: Provide a detailed description of the issue. Include any relevant information, such as steps to reproduce the issue, expected behavior, and actual behavior.
    validations:
      required: true
  - type: textarea
    id: issue_Problem
    attributes:
      label: "Issue Examples"
      description: Indicate here the examples that the issue is related to.
    validations:
      required: false
